# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5', 'macOS/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'graphics/kdiagram' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kldap' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'
