# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'graphics/kdiagram' : '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/eventviews' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kldap' : '@same'
    'pim/kmime' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'
    'pim/kpimtextedit' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows', 'macOS' ]      
